### ISSUE TITLE
Installation Problem: ImportError: cannot import name '_ColumnEntity'

### ISSUE THREAD

**Issue by arunksaha** [asharov/git-hammer#29]
(venv) user@ubuntu:~$ python -m githammer init-project foo /home/user/work/mgmt/
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/user/venv/lib/python3.6/site-packages/githammer/__init__.py", line 2, in <module>
    from .hammer import Hammer, DatabaseNotInitializedError, OldDatabaseSchemaError
  File "/home/user/venv/lib/python3.6/site-packages/githammer/hammer.py", line 24, in <module>
    from sqlalchemy_utils import create_database, database_exists
  File "/home/user/venv/lib/python3.6/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/home/user/venv/lib/python3.6/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/home/user/venv/lib/python3.6/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/home/user/venv/lib/python3.6/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/home/user/venv/lib/python3.6/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity'
(venv) user@ubuntu:~$

**Comment by sc68cal** [comment]
There must be something wrong with the dependencies published for this package on pypi 

```
 » pip install git-hammer
Collecting git-hammer
  Downloading git_hammer-0.3.1-py3-none-any.whl (23 kB)
Collecting python-dateutil
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting beautifultable
  Downloading beautifultable-1.0.1-py2.py3-none-any.whl (27 kB)
Collecting sqlalchemy-utils
  Downloading SQLAlchemy-Utils-0.36.8.tar.gz (138 kB)
     |████████████████████████████████| 138 kB 2.4 MB/s
Collecting matplotlib
  Downloading matplotlib-3.4.1-cp39-cp39-macosx_10_9_x86_64.whl (7.2 MB)
     |████████████████████████████████| 7.2 MB 3.7 MB/s
Collecting globber
  Downloading globber-0.2.1-py3-none-any.whl (8.0 kB)
Collecting gitpython
  Downloading GitPython-3.1.14-py3-none-any.whl (159 kB)
     |████████████████████████████████| 159 kB 20.7 MB/s
Collecting sqlalchemy
  Downloading SQLAlchemy-1.4.5-cp39-cp39-macosx_10_14_x86_64.whl (1.5 MB)
     |████████████████████████████████| 1.5 MB 4.0 MB/s
```

It's downloading a much more recent version of sqlalchemy despite the fact that in this git repo sqlalchemy is pinned at `sqlalchemy==1.3.12`

**Comment by asharov** [comment]
Thanks for the report! The problem was that sqlalchemy-utils wasn't compatible with the new sqlalchemy 1.4. Luckily there was a new release of sqlalchemy-utils today that fixed the problem. I updated the dependencies to require compatible versions, and fixed one issue that git-hammer had with sqlalchemy 1.4, and now everything should be working.

I did need to update the required Python version to 3.7, since some of the dependencies also require that. If you need to use Python 3.6, my recommendation is to install sqlalchemy 1.3 manually before installing git-hammer. Since the old version of git-hammer works with 1.3, pip shouldn't try to install a newer version.
