### ISSUE TITLE
Commit with a newly created empty directory causes update-project to fail

### ISSUE THREAD

**Issue by tenzo-dev** [asharov/git-hammer#7]
Fails with traceback:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "~/git/git-hammer/githammer/__main__.py", line 98, in <module>
    parsed_args.func(parsed_args)
  File "~/git/git-hammer/githammer/__main__.py", line 32, in update_project
    hammer.update_data()
  File "~/git/git-hammer/githammer/hammer.py", line 312, in update_data
    self._process_repository(repository, session)
  File "~/git/git-hammer/githammer/hammer.py", line 242, in _process_repository
    parent_commit.test_counts)
  File "~/git/git-hammer/githammer/hammer.py", line 161, in _make_diffed_commit_stats
    current_test_counts)
  File "~/git/git-hammer/githammer/hammer.py", line 122, in _blame_blob_into_line_counts
    blame = repository.git_repository.blame(commit_to_blame, path, w=True)
  File "~/git/git-hammer/venv/lib/python3.6/site-packages/git/repo/base.py", line 775, in blame
    data = self.git.blame(rev, '--', file, p=True, stdout_as_string=False, **kwargs)
  File "~/git/git-hammer/venv/lib/python3.6/site-packages/git/cmd.py", line 548, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "~/git/git-hammer/venv/lib/python3.6/site-packages/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "~/git/git-hammer/venv/lib/python3.6/site-packages/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git blame -p -w <commit> -- src/new_directory
  stderr: 'fatal: no such path src/new_directory in <commit>'
```

**Comment by asharov** [comment]
Hi, thanks for the report!

Could you explain how you created that commit? As far as I have understood, it is not possible to add a directory to a git repository, only files. I was not able to generate your situation where a directory would be attempted to be processed, so I could use some help here.

**Comment by tenzo-dev** [comment]
Unfortunately the commit is several years old and predates my involvement in this repo so I'm not sure, but I've taken another look and it seems to be because the commiter was using submodules.

user api ((<failing-commit>...) $) $ git diff <prev-commit> -- src/emptyfolder/
diff --git a/src/emptyfolder b/src/emptyfolder
new file mode 160000
index 000000000..<another-commit-id>
--- /dev/null
+++ b/src/emptyfolder
@@ -0,0 +1 @@
+Subproject commit <another-commit-id>

**Comment by asharov** [comment]
Thank you, that is helpful. I did not consider submodules yet, and apparently there are some subtleties in supporting them, based on your experience. I will try to look into this when I have time.

**Comment by asharov** [comment]
Hi @tenzo-dev, I was able to reproduce this issue with a submodule, and I believe I fixed it. Could you check out the branch `diff-ignore-submodules` and see if that fixes the problem also with your repository?
