### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 25: invalid start byte

### ISSUE THREAD

**Issue by pmajkutewicz** [asharov/git-hammer#9]
Want to test it , so cloned, fired up against one of projects and got this:

```Init time 0:00:00.001840
Repository xxxxx
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/git-hammer/githammer/__main__.py", line 98, in <module>
    parsed_args.func(parsed_args)
  File "/git-hammer/githammer/__main__.py", line 37, in add_repository
    hammer.add_repository(options.repository, options.configuration)
  File "/git-hammer/githammer/hammer.py", line 312, in add_repository
    self._process_repository(dbrepo, session)
  File "/git-hammer/githammer/hammer.py", line 252, in _process_repository
    line_counts, test_counts = self._make_full_commit_stats(repository, commit)
  File "/git-hammer/githammer/hammer.py", line 143, in _make_full_commit_stats
    lines = [line.decode('utf-8') for line in io.BytesIO(git_object.data_stream.read()).readlines()]
  File "/git-hammer/githammer/hammer.py", line 143, in <listcomp>
    lines = [line.decode('utf-8') for line in io.BytesIO(git_object.data_stream.read()).readlines()]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x93 in position 25: invalid start byte
```

Any advices?

**Comment by asharov** [comment]
Thanks for the report! It looks like your file is encoded with something other than UTF-8, and unfortunately Git Hammer currently expects files to be in UTF-8.

I don't actually see any reason for requiring UTF-8. Any text encoding should be supported for source files. I'll try to fix this problem soon.

**Comment by pmajkutewicz** [comment]
@asharov Having file name in error message would be helpful too :) - at least i'll would be able to identify and fix my file. :)

**Comment by asharov** [comment]
@pmajkutewicz I made PR #10 that should fix your problem. There's a test to reproduce it that's now passing. Could you also check that it's fixed for you?

I made a separate issue to improve error messages, since this is not the only place that could use improvement there. :-)

**Comment by pmajkutewicz** [comment]
@asharov 
OK, looks much better now:
```Commit 10080: 1:45:30.132987
Commit 10100: 1:45:55.159704
Commit 10120: 1:46:09.726807
Commit 10140: 1:46:21.105556
Commit 10160: 1:46:25.556613
Commit 10180: 1:46:33.138843
Commit 10198: Database commit time 0:00:00.479919
Commit 10200: 1:57:31.600217
Commit 10213: Database commit time 0:00:00.071966
Commit 10219: Database commit time 0:00:00.042217
Commit 10220: 2:20:33.257327
Commit 10226: Database commit time 0:00:00.049077
Commit 10240: 2:32:12.504618
Commit 10260: 2:32:33.154948
Commit 10263: Database commit time 0:00:00.154253
Commit 10280: 2:44:25.555839
Commit 10291: Database commit time 0:00:00.117344
Commit 10300: 2:56:55.245331
Commit 10301: Database commit time 0:00:00.053843
Commit 10305: Database commit time 0:00:00.034266
Commit 10320: 3:20:17.295226
```
And now looks everything is stopped. But I'm now like half way through.
